config/routes.rb
Rails.application.routes.draw do

   get 'portfolios/view' => 'portfolios#view'

  resources :portfolios
  resources :jobs
  resources :themes
  resources :sites
  get 'users/profile'
  get 'users/dash_board'
  get 'image/call' => "image#call"
  mount Ckeditor::Engine => '/ckeditor'

  resources :posts do
    resources :comments
  end  

  devise_for :users, :controllers => {omniauth_callbacks: 'omniauth_callbacks', :registrations => "registrations"}

  root 'home#index'

  get 'page/routing_error'

  match 'about' => 'page#about', :as => :about, via: [:get, :post]
  match 'contact' => 'page#contact', :as => :contact, via: [:get, :post]

  if Rails.env.production?
    match '*a' => 'page#routing_error', :as => :routing_error, via: [:get, :post]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :body

  belongs_to :post
  belongs_to :user

end

app/models/image.rb
class Image < ActiveRecord::Base
belongs_to :site
belongs_to :portfolio
belongs_to :user

 def self.save(upload)
    name =  upload['upload'].original_filename
    random=rand(11 .. 11150)
     fname=random.to_s + '_' + name
    directory = "public/images/user"
    # create the file path
    path = File.join(directory, fname)
    # write the file
    File.open(path, "wb") { |f| f.write(upload['upload'].read) }
      upload['site_id'] = Portfolio.last.id if upload['site_id'].blank?
    a=Image.find_by_site_id(upload['site_id'])
    a= Image.new if a.nil?
    a.user_id=upload['user_id']
    a.site_name=upload['site_name']
    a.site_id=upload['site_id']
    a.image_url='/images/user/'+fname
    a.image_name=fname
    a.save!
    p=Portfolio.find(upload['site_id'])
    p.image_id=Image.last.id
    p.save
  end

def self.destroy(upload)
Image.find_by_site_id(upload['id']).delete rescue 'nil'
end

end

app/models/job.rb
class Job < ActiveRecord::Base
  validates_presence_of :title
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
    belongs_to :user
    has_many :images
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  scope :published, lambda { where(is_published: true) }

  validates :title, presence: true,
            length: {minimum: 5}

  validates_presence_of :body
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :name
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :posts
  has_many :comments

  has_many :portfolios
  has_many :images
  has_one  :site


  before_create :generate_unique_user
  after_create :auto_create_subdomain


  def auto_create_subdomain
    subdomain = self.username.gsub(/[.]/, '')
    self.subdomain = subdomain
    self.save!
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.gender = auth.info.gender
      user.image = auth.info.image
    end
  end


  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def generate_unique_user
    if self.username.blank?
      username = self.email.split("@").first
      username = username.downcase
      #new_username = username.dup
      self.username = unique_username(username)
    end
  end

  def unique_username(username)
    num = 1
    new_username = username
    p new_username
    user = User.where(:username => 'er.ahmad.hassan').first
    p user
    p User.find_by_username(new_username)
    while User.where(username: new_username).first  do
      num +=1
      new_username = "#{username}#{num}"
      p "New Username= #{new_username}"
    end
    return new_username
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  def index
    @jobs = Job.all
    respond_with(@jobs)
  end

  def show
    respond_with(@job)
  end

  def new
    @job = Job.new
    respond_with(@job)
  end

  def edit
  end

  def create
    @job = Job.new(job_params)
    @job.save
    respond_with(@job)
  end

  def update
    @job.update(job_params)
    respond_with(@job)
  end

  def destroy
    @job.destroy
    respond_with(@job)
  end

  private
  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:title, :description)
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def routing_error
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  respond_to :html, :json

  #layout 'blog_default'

  def index
    @post = Post.all
    respond_with(@posts)
  end

  def show
    respond_with(@post)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.save
    respond_with(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :user_id, :published_at, :is_published)
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  respond_to :html, :json
  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_theme
    @theme = Theme.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def theme_params
    params.require(:theme).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then 'alert alert-info'
      when :success then 'alert alert-success'
      when :error then 'alert alert-danger'
      when :alert then 'alert alert-danger'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def which_user(id)
    user=User.find(id)
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/themes/_form.html.erb
<%= form_for(@theme) do |f| %>
  <% if @theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
      <% @theme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-grou">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="form-grou">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
    <div class="form-group">
        <%= f.submit "Create Theme", :class=>"btn btn-primary" %>
        <%= link_to 'Back', themes_path, :class=>"btn btn-info" %>
    </div>
<% end %>

app/views/themes/edit.html.erb
<div class="container">
<h1>Editing theme</h1>

<%= render 'form' %>


</div>

app/views/themes/index.html.erb
<div class="container">
    <h1>Listing Sites</h1>

    <div class="table-responsive">
        <%= link_to 'New Theme', new_theme_path %>

        <table class="table">
            <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>


                <th colspan="3">Action</th>
            </tr>
            </thead>

            <tbody>
            <% @themes.each do |theme| %>
                <tr>
                    <td><%= theme.name %></td>
                    <td><%= theme.description %></td>
                    <td><%= link_to 'Show', theme %></td>
                    <td><%= link_to 'Edit', edit_theme_path(theme) %></td>
                    <td><%= link_to 'Destroy', theme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
            <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/themes/new.html.erb
<div class="container">
<h1>New theme</h1>

<%= render 'form' %>

</div>

app/views/themes/show.html.erb
<div class="container">
    <p id="notice"><%= notice %></p>

    <p>
        <strong>Name:</strong>
        <%= @theme.name %>
    </p>

    <p>
        <strong>Description:</strong>
        <%= @theme.description %>
    </p>

    <%= link_to 'Edit', edit_theme_path(@theme) %> |
    <%= link_to 'Back', themes_path %>


</div>