config/routes.rb
Rails.application.routes.draw do

   get 'portfolios/view' => 'portfolios#view'

  resources :portfolios
  resources :jobs
  resources :themes
  resources :sites
  get 'users/profile'
  get 'users/dash_board'
  get 'image/call' => "image#call"
  mount Ckeditor::Engine => '/ckeditor'

  resources :posts do
    resources :comments
  end  

  devise_for :users, :controllers => {omniauth_callbacks: 'omniauth_callbacks', :registrations => "registrations"}

  root 'home#index'

  get 'page/routing_error'

  match 'about' => 'page#about', :as => :about, via: [:get, :post]
  match 'contact' => 'page#contact', :as => :contact, via: [:get, :post]

  if Rails.env.production?
    match '*a' => 'page#routing_error', :as => :routing_error, via: [:get, :post]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :body

  belongs_to :post
  belongs_to :user

end

app/models/image.rb
class Image < ActiveRecord::Base
belongs_to :site
belongs_to :portfolio
belongs_to :user

 def self.save(upload)
    name =  upload['upload'].original_filename
    random=rand(11 .. 11150)
     fname=random.to_s + '_' + name
    directory = "public/images/user"
    # create the file path
    path = File.join(directory, fname)
    # write the file
    File.open(path, "wb") { |f| f.write(upload['upload'].read) }
      upload['site_id'] = Portfolio.last.id if upload['site_id'].blank?
    a=Image.find_by_site_id(upload['site_id'])
    a= Image.new if a.nil?
    a.user_id=upload['user_id']
    a.site_name=upload['site_name']
    a.site_id=upload['site_id']
    a.image_url='/images/user/'+fname
    a.image_name=fname
    a.save!
    p=Portfolio.find(upload['site_id'])
    p.image_id=Image.last.id
    p.save
  end

def self.destroy(upload)
Image.find_by_site_id(upload['id']).delete rescue 'nil'
end

end

app/models/job.rb
class Job < ActiveRecord::Base
  validates_presence_of :title
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
    belongs_to :user
    has_many :images
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  scope :published, lambda { where(is_published: true) }

  validates :title, presence: true,
            length: {minimum: 5}

  validates_presence_of :body
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :name
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :posts
  has_many :comments

  has_many :portfolios
  has_many :images
  has_one  :site


  before_create :generate_unique_user
  after_create :auto_create_subdomain


  def auto_create_subdomain
    subdomain = self.username.gsub(/[.]/, '')
    self.subdomain = subdomain
    self.save!
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.gender = auth.info.gender
      user.image = auth.info.image
    end
  end


  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def generate_unique_user
    if self.username.blank?
      username = self.email.split("@").first
      username = username.downcase
      #new_username = username.dup
      self.username = unique_username(username)
    end
  end

  def unique_username(username)
    num = 1
    new_username = username
    p new_username
    user = User.where(:username => 'er.ahmad.hassan').first
    p user
    p User.find_by_username(new_username)
    while User.where(username: new_username).first  do
      num +=1
      new_username = "#{username}#{num}"
      p "New Username= #{new_username}"
    end
    return new_username
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  def index
    @jobs = Job.all
    respond_with(@jobs)
  end

  def show
    respond_with(@job)
  end

  def new
    @job = Job.new
    respond_with(@job)
  end

  def edit
  end

  def create
    @job = Job.new(job_params)
    @job.save
    respond_with(@job)
  end

  def update
    @job.update(job_params)
    respond_with(@job)
  end

  def destroy
    @job.destroy
    respond_with(@job)
  end

  private
  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then 'alert alert-info'
      when :success then 'alert alert-success'
      when :error then 'alert alert-danger'
      when :alert then 'alert alert-danger'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def which_user(id)
    user=User.find(id)
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_footer.html.erb
<!-- Footer Part-->
<div style="width: 100%; height:20px; background-color: #211947"></div>
<div class="container">
    <div class="row" style="padding-top:20px;padding-bottom:20px;float: left">
        <div class="col-md-2 ">
            <image src="../images/footer_logo.png"></image>
        </div>
        <div class="col-md-2 footertext">
            <br/>
            #318,16th Cross, 5th Phase<br/>
            Bangalore - 560078<br/>
            India
            08040943507<br/>
            support@eMangu.com
        </div>
        <div class="col-md-2 footertext">
            <br/>

            <div class="sitemap">Sitemap</div>
            <div class="sitemap_list1">
               <a href="#"> Free website builder</a></br>
               <a href="#"> Business features</a></br>
               <a href="#"> Free SEO guide</a></br>
               <a href="#"> Active competitions</a></br>
               <a href="#"> Build a free website</a></br>
               <a href="#"> Free e-commerce shop</a>
            </div>
            <br/> <br/>
        </div>

        <div class="col-md-2 footertext">
            <br/>

            <div class="sitemap">RECRUITMENT</div>
            <br/>

            <div>
                We are frequently on the lookout for new talent!
            </div>
        </div>
        <div class="col-md-2 footertext">
            <br/>

            <div class="footertext">
                <div class="social">FOLLOWS US</div>
                <image src="../images/social-media-gft.png"></image>
            </div>
        </div>
    </div>
</div>
<div class="panel-footer" align="center">Copyright &copy;2014 Emangu. All rights reserved.</div>

<!--Footer Part Ends-->

app/views/common/_header.html.erb
<!--Header Part-->
<header>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="/">
                        <image src="../images/logo.png" width="200px" height="50;"></image>
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="menu_item"><a href="/"><span class="fa fa-home fa-fw"></span>&nbsp; Home</a></li>
                        <li class="menu_item"><a href="/posts"><span class="fa fa-book fa-fw"></span>&nbsp;Blog</a></li>
                        <li class="menu_item"><a href="/"><span class="fa fa-cloud fa-fw"></span>&nbsp;Explore</a></li>
                        <li class="menu_item"><a href="#"><span class="fa fa-trophy fa-fw"></span>&nbsp;About</a></li>
                        <li class="menu_item"><a href="#"><span class="fa fa-phone fa-spin"></span>Contact</a></li>
                        <li class="drop_down">
                         <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                                    <li><a href="/portfolios">Home</a></li>
                                    <li><a href="/portfolios/view">Gallery</a></li>
                            </ul>
                        </li>
                    </ul>
                    <% if user_signed_in? %>

                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= (current_user.email) %>
                                    <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#"><span class="glyphicon glyphicon-user"></span>Profile</a></li>
                                    <li><a href="#"><span class="fa fa-cog"></span>Account</a></li>
                                    <li class="divider"></li>
                                    <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
                                </ul>
                            </li>
                        </ul>
                    <% else %>
                        <ul class="nav navbar-nav navbar-right">

                            <li>
                                <a href="#" data-toggle="modal" data-target="#myModal">Login/Signup&nbsp;&nbsp;<span class="fa fa-unlock-alt"></span>
                                    <up></up>
                                </a>
                        </ul>

                    <% end %>
                </div>
            </div>
        </div>
    </nav>
</header>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="padding-bottom:20px;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h3 class="modal-title" id="myModalLabel">Login or Sign-Up</h3>
            </div>

            <div class="modal-body">


                <div class="login_margin1">
                    <p><b>Sign-in Now! for Emangu</b>,</p>
                </div>

                <div class="login_margin_socialmedia">
                    <p>
                        <%= link_to user_omniauth_authorize_path(:facebook) do %>
                            <button class="btn-facebook">  <i class="fa fa-facebook"></i> | Facebook</button>
                        <% end %>

                        <button class="btn-twitter"><i class="fa fa-twitter"></i> | Twitter</button>
                        <button class="btn-google-plus"><i class="fa fa-google-plus"></i> | Google +</button>
                        <br></p>
                </div>

                <div class="login_margin2">
                    it's free and always will be..</p>

                </div>

                <div id="form_login">
                    <%= form_for(:user, :url => session_path(:user)) do |f| %>
                        <div class="row">
                            <div class="col-md-2"></div>
                            <div class="form-group col-md-8">
                                <div class="input-group margin-bottom-sm">
                                    <span class="input-group-addon"><i class="fa fa-envelope-o fa-fw"></i></span>
                                    <%= f.email_field :email, autofocus: true, :class => "form-control", :required => true, :placeholder => "Enter Email-id" %>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-2"></div>
                            <div class="form-group col-md-8">
                                <div class="input-group margin-bottom-sm">
                                    <span class="input-group-addon"><i class="fa fa-key fa-fw"></i></span>
                                    <%= f.password_field :password, autocomplete: "off", :class => "form-control", :required => true, :placeholder => "Enter Your Password" %>
                                </div>
                            </div>
                        </div>
                        <div class="row form_margin">
                            <div class="form-group col-md-9">
                                <%= f.check_box :remember_me %>
                                <%= f.label :remember_me %>
                                <label>&nbsp;&nbsp;&nbsp;</label>
                                <%= link_to "Forgot your password?", new_password_path(:user) %>
                            </div>
                        </div>
                        <div class="col-md-4"></div>
                        <%= f.submit "Log in", :class => "btn btn-primary", :id => "login_toggle" %>
                        <button type="button" class="btn btn-success" id="register_toggle">Create New Account</button>

                        </div>

                    <% end %>
                    </div>

            <div id="form_register">
                <%= form_for(:user, :url => registration_path(:user)) do |f| %>
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="form-group col-md-8">


                            <div class="input-group margin-bottom-sm">
                                <span class="input-group-addon"><i class="fa fa-envelope-o fa-fw"></i></span>
                                <%= f.email_field :email, autofocus: true, :required=>true, :class => "form-control", :placeholder => "Enter Email-id" %>
                            </div>

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="form-group col-md-8">


                   <div class="input-group margin-bottom-sm">
                                <span class="input-group-addon"><i class="fa fa-key fa-fw"></i></span>
                                <%= f.password_field :password, autocomplete: "off",:required=>true, :class => "form-control", :placeholder => "Enter Password" %>
                            </div>

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-2">
                        </div>
                        <div class="form-group col-md-8">

                            <div class="input-group margin-bottom-sm">
                                <span class="input-group-addon"><i class="fa fa-key fa-fw"></i></span>
                                <%= f.password_field :password_confirmation, autocomplete: "off", :required=>true, :class => "form-control", :placeholder => "Confirm Password" %>
                            </div>

                        </div>
                    </div>


                    <div class="row">
                        <div class="col-md-4"></div>
                        <%= f.submit "Create New Account", :class => "btn btn-success" %>

                        <button type="button" class="btn btn-primary" id="login_toggle1">Login</button>
                    </div>
                <% end %>
            </div>

        </div>


    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#login_toggle1').click(function () {
            $('#form_login').show();
            $('#form_register').hide();
        })
        $('#register_toggle').click(function () {
            $('#form_login').hide();
            $('#form_register').show();
        })
    });

</script>


<!--Header Part Ends-->

app/views/page/about.html.erb
<div class="container">
    <div class="row" style="text-align: center">
            <h1 style="color:gray;">About Emangu </h1>

            <h4 style="color:#091b40; text-justify: auto">We are going to leader in the global marketplace and among the top 10 technology firms in the world.
                Our continued rapid growth is a testament to the certainty our clients experience every day.
                We add real value to global organizations through domain expertise plus solutions with proven success in the field and world-class service.
                It’s how we keep you moving forward.</h4>
    </div>
</div>

app/views/page/contact.html.erb
<div class="container">
    <div class="row" style="text-align: center">
            <h1 style="color:darkgray;">Contact Page</h1>
            <p>
                #318,16th Cross, 5th Phase</br>
                Bangalore - 560078</br>
                India 08040943507</br>
                support@eMangu.com </br>
            </p>
    </div>
</div>

app/views/page/routing_error.html.erb
<div class="container">
    <div class="row" style="text-align: center">
            <h1 style="color:red;">Page Not Found</h1>
            <h2 style="color:red;">Sorry, the page you are looking for has moved, or doesn't exist!</h2>
            <h2 style="color:#091b40">Please re-check the URL or Contact to site admin</h2>
    </div>
</div>

app/views/templates/p1/_about.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Emangu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/media.css" rel="stylesheet">
  </head>
  <body>

    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand nav-link" href="#top">Emangu</a>
        </div> <!-- /.navbar-header -->

        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../../../../public/p1/index.html">Home</a></li>
            <li><a href="../../../../public/p1/portfolio.html">Portfolio</a></li>
            <li><a href="../../../../public/p1/contact.html">Contact</a></li>
            <li><a href="#">About</a></li>
          </ul>
        </div> <!-- /.navbar-collapse -->
      </div> <!-- /.container -->
    </nav> <!-- /.navbar -->

    <div class="jumbotron">
      <div class="container">
        <h1>Welcome to Photography</h1>
        <br>
      </div> <!-- /.container -->
    </div> <!-- /.jumbotron -->

    <div class="spacer"></div>

    <div class="container">
      <div class="row">
        <div class="col-md-4 col-sm-6 feature-text">
          <h3>About</h3>
          <p>
           I'm a paragraph. Click here to add your own text and edit me. It’s easy. Just click “Edit Text” or double click me and you can start adding your own content and make changes to the font. Feel free to drag and drop me anywhere you like on your page. I’m a great place for you to tell a story and let your users know a little more about you.
This is a great space to write long text about your company and your services. You can use this space to go into a little more detail about your company. Talk about your team and what services you provide. Tell your visitors the story of how you came up with the idea for your business and what makes you different from your competitors. Make your company stand out and show your visitors who you are. Tip: Add your own image by double clicking the image and clicking Change Image.
          </p>
        </div> <!-- /.feature-text -->
        <div class="col-md-8 col-sm-6">
          <img src="img/stock2.jpg" class="feature-photo">
        </div> <!-- /.col-md-8 -->
      </div> <!-- /.row -->

      <div class="spacer"></div>

    </div> <!-- /.container -->

    <footer>
      <div class="container clearfix">
        <p class="pull-left">
          Copyright &copy; Emangu 2014
        </p>
        
      </div> <!-- /.container -->
    </footer>

   
      <script src="js/jquery.js"></script>
      <script src="js/bootstrap.min.js"></script>
   
  </body>
</html>

app/views/templates/p1/_contact.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Emangu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/media.css" rel="stylesheet">
  </head>
  <body>

    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand nav-link" href="#top">Emangu</a>
        </div> <!-- /.navbar-header -->

        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="index.html">Home</a></li>
            <li><a href="portfolio.html">Portfolio</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="../../app/views/users/templates/about.html">About</a></li>
          </ul>
        </div> <!-- /.navbar-collapse -->
      </div> <!-- /.container -->
    </nav> <!-- /.navbar -->

    <div class="jumbotron">
      <div class="container">
        <h1>Welcome to Photography</h1>
        <br>
      </div> <!-- /.container -->
    </div> <!-- /.jumbotron -->

    <div class="spacer"></div>

    <div class="container">
      <div class="row">
        <div class="col-md-4 col-sm-6 feature-text">
          <h3>Contact</h3>
          <p>
		#318,16th Cross,<br/>
		JP Nagar 5th Phase,Banglore<br/>
		Phone No:08040943507
	</p>
	<form>
		<div class="input-group">
	  		<span class="input-group-addon">Name</span>
	  		<input type="text" class="form-control" placeholder="Name">
		</div>
		<br/>
		<div class="input-group">
	  		<span class="input-group-addon">Email</span>
	  		<input type="text" class="form-control" placeholder="Email Id">
		</div>
		<br/>
		<div class="input-group">
	  		<span class="input-group-addon">Subject</span>
	  		<input type="text" class="form-control" placeholder="Subject">
		</div>
		<br/>
		<div class="input-group">
	  		<span class="input-group-addon">Message</span>
	  		<textarea type="text" class="form-control" placeholder="Message"></textarea>
		</div>
		<br/>
		<button class="btn btn-info pull-right" >Send</button>
	</form>
        </div> <!-- /.feature-text -->
        <div class="col-md-8 col-sm-6">
          <img src="img/stock3.jpg" class="feature-photo">
        </div> <!-- /.col-md-8 -->
      </div> <!-- /.row -->

      <div class="spacer"></div>

    </div> <!-- /.container -->

    <footer>
      <div class="container clearfix">
        <p class="pull-left">
          Copyright &copy; Emangu 2014
        </p>
        
      </div> <!-- /.container -->
    </footer>

    
      <script src="js/jquery.js"></script>
      <script src="js/bootstrap.min.js"></script>
   
  </body>
</html>

app/views/templates/p1/_portfolio.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Emangu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/media.css" rel="stylesheet">
<link href="css/jquery.fancybox.css" rel="stylesheet">
<link href="css/jquery.fancybox-thumbs.css" rel="stylesheet">
<script src="js/jquery.js"></script>
<script src="js/jquery.fancybox.js"></script>
<script src="js/jquery.fancybox-thumbs.js"></script>
<style>
.hidden {
    display: none;
}
</style>
<script>
	$(document).ready(function(){
	$('.fancybox-thumbs').fancybox({
                prevEffect : 'none',
                nextEffect : 'none',

                closeBtn  : false,
                arrows    : false,
                nextClick : true,

                helpers : {
                    thumbs : {
                        width  : 50,
                        height : 50
                    }
                }
            });
	});
</script>
  </head>
  <body>

    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand nav-link" href="#top">Emangu</a>
        </div> <!-- /.navbar-header -->

        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Home</a></li>
            <li><a href="portfolio.html">Portfolio</a></li>
            <li><a href="contact.html">Contact</a></li>
            <li><a href="../../app/views/users/templates/about.html">About</a></li>
          </ul>
        </div> <!-- /.navbar-collapse -->
      </div> <!-- /.container -->
    </nav> <!-- /.navbar -->

    <div class="jumbotron">
      <div class="container">
        <h1>Welcome to Photography</h1>
        <br>
      </div> <!-- /.container -->
    </div> <!-- /.jumbotron -->

    <div class="spacer"></div>

    <div class="container">
      <div class="row">
	<div class="col-md-12 col-sm-6 feature-text" style="text-align:center;">
		  <h3>Photography</h3>
	</div>
       <div class="col-lg-3 col-sm-4 col-xs-6"><a class="fancybox-thumbs" data-fancybox-group="thumb1" href="img/travel/01.jpg"><img class="thumbnail img-responsive" src="img/travel/01.jpg"></a></div>
      <div class="col-lg-3 col-sm-4 col-xs-6"><a class="fancybox-thumbs" data-fancybox-group="thumb1" href="img/travel/02.jpg"><img class="thumbnail img-responsive" src="img/travel/02.jpg"></a></div>
      <div class="col-lg-3 col-sm-4 col-xs-6"><a  class="fancybox-thumbs" data-fancybox-group="thumb1"  href="img/travel/03.jpg"><img class="thumbnail img-responsive" src="img/travel/03.jpg"></a></div>
      <div class="col-lg-3 col-sm-4 col-xs-6"><a  class="fancybox-thumbs" data-fancybox-group="thumb1"  href="img/travel/04.jpg"><img class="thumbnail img-responsive" src="img/travel/04.jpg"></a></div>
      <div class="col-lg-3 col-sm-4 col-xs-6"><a  class="fancybox-thumbs" data-fancybox-group="thumb1"  href="img/travel/05.jpg"><img class="thumbnail img-responsive" src="img/travel/05.jpg"></a></div>
      <div class="col-lg-3 col-sm-4 col-xs-6"><a  class="fancybox-thumbs" data-fancybox-group="thumb1"  href="img/travel/06.jpg"><img class="thumbnail img-responsive" src="img/travel/06.jpg"></a></div>
      <div class="col-lg-3 col-sm-4 col-xs-6"><a  class="fancybox-thumbs" data-fancybox-group="thumb1"  href="img/travel/07.jpg"><img class="thumbnail img-responsive" src="img/travel/07.jpg"></a></div>
      <div class="col-lg-3 col-sm-4 col-xs-6"><a  class="fancybox-thumbs" data-fancybox-group="thumb1"  href="img/travel/08.jpg"><img class="thumbnail img-responsive" src="img/travel/08.jpg"></a></div>
      <div class="col-lg-3 col-sm-4 col-xs-6"><a  class="fancybox-thumbs" data-fancybox-group="thumb1"  href="img/travel/09.jpg"><img class="thumbnail img-responsive" src="img/travel/09.jpg"></a></div>
      <div class="col-lg-3 col-sm-4 col-xs-6"><a  class="fancybox-thumbs" data-fancybox-group="thumb1"  href="img/travel/10.jpg"><img class="thumbnail img-responsive" src="img/travel/10.jpg"></a></div>
      <div class="col-lg-3 col-sm-4 col-xs-6"><a  class="fancybox-thumbs" data-fancybox-group="thumb1"  href="img/travel/11.jpg"><img class="thumbnail img-responsive" src="img/travel/11.jpg"></a></div>
      <div class="col-lg-3 col-sm-4 col-xs-6"><a  class="fancybox-thumbs" data-fancybox-group="thumb1"  href="img/travel/12.jpg"><img class="thumbnail img-responsive" src="img/travel/12.jpg"></a></div>
      </div> <!-- /.row -->

      <div class="spacer"></div>

    </div> <!-- /.container -->

    <footer>
      <div class="container clearfix">
        <p class="pull-left">
          Copyright &copy; Emangu 2014
        </p>
        
      </div> <!-- /.container -->
    </footer>

   
      <script src="js/bootstrap.min.js"></script>
   
  </body>
</html>

app/views/templates/p2/_about.html.erb
<div class="animate1" style="">
<br/>
<div style="width:600px;margin-left:30px;padding:20px;background-color: rgba(255, 255, 255, 0.7);" class="pull-
left">
	<h2>Emangu</h2>
	<h4>About</h4>
	<p>I'm a paragraph. Click here to add your own text and edit me. It’s easy. Just click “Edit Text” or double click me and you can start adding your own content and make changes to the font. Feel free to drag and drop me anywhere you like on your page. I’m a great place for you to tell a story and let your users know a little more about you.
This is a great space to write long text about your company and your services. You can use this space to go into a little more detail about your company. Talk about your team and what services you provide. Tell your visitors the story of how you came up with the idea for your business and what makes you different from your competitors. Make your company stand out and show your visitors who you are. Tip: Add your own image by double clicking the image and clicking Change Image.</p>
</div>
</div>
  

app/views/templates/p2/_footer.html.erb
<div class="navbar container-fluid"  style="padding-top:30px;">
    <h5 style="text-align:center;"><span class="label label-default">Copyright &copy; 2014 by emangu Terms of Service </span></h5>
  </div>
</div>